version: '3.9'

services:
  rest:
    build:
      context: ./Servidor/Rest
    ports:
      - "5001:5001"
    volumes:
      - ./Servidor/XML:/app/XML

  soap:
    build:
      context: ./Servidor/Soap
    ports:
      - "5000:5000"
    volumes:
      - ./Servidor/XML:/app/XML

  grpc:
    build:
      context: ./Servidor/gRPC
    ports:
      - "50051:50051"
    volumes:
      - ./Servidor/XML:/app/XML

  graphql:
    build:
      context: ./Servidor/graphQL
    ports:
      - "5002:5002"
    volumes:
      - ./Servidor/XML:/app/XML
