# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import books_pb2 as books__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in books_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub(object):
    """Serviço para consultas via gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBook = channel.unary_unary(
                '/books.BookService/GetBook',
                request_serializer=books__pb2.BookRequest.SerializeToString,
                response_deserializer=books__pb2.BookResponse.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_stream(
                '/books.BookService/ListBooks',
                request_serializer=books__pb2.Empty.SerializeToString,
                response_deserializer=books__pb2.BookResponse.FromString,
                _registered_method=True)


class BookServiceServicer(object):
    """Serviço para consultas via gRPC
    """

    def GetBook(self, request, context):
        """Método unário para buscar um livro por nome
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Método de streaming para listar todos os livros (opcional)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=books__pb2.BookRequest.FromString,
                    response_serializer=books__pb2.BookResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=books__pb2.Empty.FromString,
                    response_serializer=books__pb2.BookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('books.BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """Serviço para consultas via gRPC
    """

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.BookService/GetBook',
            books__pb2.BookRequest.SerializeToString,
            books__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/books.BookService/ListBooks',
            books__pb2.Empty.SerializeToString,
            books__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
