# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livro.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'livro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blivro.proto\"\x1c\n\x0cLivroRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\";\n\rLivroResponse\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05\x61utor\x18\x02 \x01(\t\x12\r\n\x05preco\x18\x03 \x01(\x01\x32>\n\x0cLivroService\x12.\n\rProcurarLivro\x12\r.LivroRequest\x1a\x0e.LivroResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIVROREQUEST']._serialized_start=15
  _globals['_LIVROREQUEST']._serialized_end=43
  _globals['_LIVRORESPONSE']._serialized_start=45
  _globals['_LIVRORESPONSE']._serialized_end=104
  _globals['_LIVROSERVICE']._serialized_start=106
  _globals['_LIVROSERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
